### ISSUE TITLE
No data showing in serial monitor

### ISSUE THREAD

**Issue by RashikShahjahan** [opensensinglab/tfmini#10]
We are using the example BasicReading code included with he library. Our setup is the same as this video:
https://www.youtube.com/watch?v=VhbFbxyOI1k&t=1092s&fbclid=IwAR3khhu7QYcBBaMKj1so-swQpUtuHWnf2FYCyCYwWypNeV1Y2j3mluIvE7A

But when we run the code and look at the serial monitor, the monitor only shows 'Initializing...'

What could be the problem?

Thank you.

**Comment by luke-pritch** [comment]
I am also experiencing the same issue, I have a logic level converter setup but I am using a particle photon board instead. I would much appreciate any assistance on this.

**Comment by RashikShahjahan** [comment]
Problem disappeared when we ditched the logic converter with a divider circuit.

**Comment by luto65** [comment]
Sorry can you please explain what you mean with "when we ditched the logic converter with a divider circuit" ?  I am experiencing the same issue, I have the logic level converter setup ....

**Comment by luto65** [comment]
I have Arduino MEGA 2560, appropriately connected to a LLC and then the TFmini accordingly wired.
Using the "BasicReading" and the SoftwareSerial it works very nicely.
The problems I had were appearing when using the Serial2 or Serial3 (avoiding the SoftwareSerial) and also when connecting wires were not appropriately hidden from the sensor so that they were interferring with the data collection. Now everything works very smoothly, thankyou.
